### ISSUE TITLE
Add instructions for local build of site to README

### ISSUE THREAD

**Issue by etcadinfinitum** [UWB-ACM/website-example-2#1]
- [x] Add instructions for ngrok
- [x] Add instructions for jekyll

**Comment by etcadinfinitum** [comment]
@Chris-Johnston I am still unfamiliar with ngrok, would you be willing to add instructions to build/serve locally?

**Comment by Chris-Johnston** [comment]
Ngrok instructions are being worked on here: https://github.com/UWB-ACM/Hackathon-Docs/pull/4
